Repository RAF-SI-2022/Bolnica-2-Backend, pull requests merged in 2023-04, with the labels that each got.

#96 Dodati unit testovi za SchedMedExamController
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/ScheduledMedExamSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/SchedMedExaminationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/SchedMedExaminationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/SchedMedExaminationServiceTest.java
Labels: size/L

#99 Karton update novak
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/HealthRecordController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/AddAllergyRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/AddVaccinationRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/CreateExaminationReportRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/UpdateHealthRecordRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/AllergenListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/AllergenResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/BasicHealthRecordResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/ExtendedAllergyResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/ExtendedVaccinationResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/MessageResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/VaccineListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/VaccineResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/HealthRecordMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Allergen.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Diagnosis.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Vaccine.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/healthrecord/BloodType.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AllergenRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/DiagnosisRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HealthRecordRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/MedicalHistoryRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VaccineRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/HealthRecordService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HealthRecordServiceImpl.java
Labels: kind/backend, size/XL

#105 Dodati integracioni testovi za schedMedExam, Izmenjen response za search rutu
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamExtendedResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/ScheduledMedExamRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/SchedMedExaminationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/HttpUtils.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/JwtUtil.java
  patient-service/src/main/resources/application-dev.yaml
  patient-service/src/test/java/com/raf/si/patientservice/integration/CucumberConfig.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/CucumberTests.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/SchedMedExaminationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsCreate.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsDelete.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsGet.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsUpdate.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/SchedMedExaminationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/SchedMedExaminationServiceTest.java
  patient-service/src/test/resources/features/patientExamService/patientService.features
  patient-service/src/test/resources/features/schedMedExamController/schedMedExam-controller-tests.feature
  patient-service/src/test/resources/junit-platform.properties
Labels: kind/backend, size/XL

#110 Dodati endpoint-i za odeljenje i bolnicu, dodati testovi
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/PatientController.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/controller/DepartmentController.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/DepartmentResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/DoctorResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/HospitalResponse.java
  user-service/src/main/java/com/raf/si/userservice/mapper/DepartmentMapper.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/Profession.java
  user-service/src/main/java/com/raf/si/userservice/repository/DepartmentRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/HospitalRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/DepartmentService.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/DepartmentServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/departmentcontroller/DepartmentControllerSteps.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsGet.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/DepartmentControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/DepartmentServiceTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
  user-service/src/test/resources/features/departmentcontroller/department-controller-tests.feature
  user-service/src/test/resources/features/usercontroller/user-controller-tests.feature
Labels: kind/backend

#120 integracioni testovi za karton update, small bugfixes
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/HealthRecordMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/MedicalHistoryRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VaccinationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HealthRecordServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/CucumberTests.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/healthRecordController/HealthRecordControllerGetSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/healthRecordController/HealthRecordControllerUpdateHealthRecordSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/PatientControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HealthRecordServiceTest.java
  patient-service/src/test/resources/features/healthRecordController/health-record-controller-tests.feature
Labels: size/XXL

#121 Refaktorisan kod
  patient-service/src/main/java/com/raf/si/patientservice/mapper/HealthRecordMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HealthRecordServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/CucumberTests.java
Labels: kind/backend

#125 Dodat model za stacionarno lecenje
  patient-service/src/main/java/com/raf/si/patientservice/model/Appointment.java
  patient-service/src/main/java/com/raf/si/patientservice/model/DischargeList.java
  patient-service/src/main/java/com/raf/si/patientservice/model/HospitalRoom.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Hospitalization.java
  patient-service/src/main/java/com/raf/si/patientservice/model/MedicalReport.java
  patient-service/src/main/java/com/raf/si/patientservice/model/PatientCondition.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Visit.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/appointment/AppointmentStatus.java
Labels: kind/backend

#118 Kt2 uputi
  laboratory-service/pom.xml
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/bootstrap/BootstrapData.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/controllers/LabExamController.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/controllers/ReferralController.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/controllers/TestController.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/CreateLabExamRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/CreateReferralRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/UpdateLabExamStatusRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/LabExamResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/ReferralListResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/ReferralResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/UserResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/LabExamMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/ReferralMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/Referral.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabWorkOrderRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ScheduledLabExamRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/filtering/filter/LabExamFilter.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/filtering/specification/LabExamSpecification.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/LabExamService.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/ReferralService.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/LabExamServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/ReferralServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/utils/HttpUtils.java
  laboratory-service/src/main/resources/application.yaml
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/CucumberConfig.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/CucumberTests.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/UtilsHelper.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/labexamcontroller/LabExamControllerStepsCount.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/labexamcontroller/LabExamControllerStepsCreate.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/labexamcontroller/LabExamControllerStepsGet.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/labexamcontroller/LabExamControllerStepsUpdate.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsCreate.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsDelete.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsGet.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsHistory.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsUnprocessed.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/controller/LabExamControllerTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/controller/ReferralControllerTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/LabExamServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
  laboratory-service/src/test/resources/features/labexamcontroller/labexam-controller-tests.feature
  laboratory-service/src/test/resources/features/referralcontroller/referral-controller-tests.feature
  laboratory-service/src/test/resources/junit-platform.properties
Labels: size/XXL

#126 Dodate permisije za dobijanje liste svih doktora
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
Labels: kind/backend

#128 Dodat endpoint za department i promena dto-a dodavanjem bolnice u res…
  user-service/src/main/java/com/raf/si/userservice/controller/DepartmentController.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/DepartmentResponse.java
  user-service/src/main/java/com/raf/si/userservice/mapper/DepartmentMapper.java
  user-service/src/main/java/com/raf/si/userservice/repository/DepartmentRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/DepartmentService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/DepartmentServiceImpl.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsGet.java
Labels: kind/backend, size/S

#115 Lab work order features #2
  .DS_Store
  .gitignore
  laboratory-service/pom.xml
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/controller/WorkOrderController.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/order/OrderHistoryForLabRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/order/OrderHistoryRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/request/order/SaveResultRequest.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/AnalysisParameterResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/AnalysisResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/AnalysisResultResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/CreateOrderResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/OrderHistoryResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/OrderResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/ResultResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/SaveResultResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/VerifyResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/OrderMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/user/Profession.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/AnalysisParameterResultRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabAnalysisRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabWorkOrderRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/services/WorkOrderService.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/services/impl/WorkOrderServiceImplementation.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/controller/WorkOrderControllerTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
  user-service/.DS_Store
Labels: size/XL

#133 pocetak ci/prow
  .prow/laboratory-service.yaml
  .prow/patient-service.yaml
  .prow/user-service.yaml
  laboratory-service/pom.xml
  patient-service/pom.xml
  user-service/pom.xml
Labels: kind/backend, size/L

#136 use images from harbor in docker-compose
  build_images.sh
  docker-compose.yaml
Labels: size/S

#146 add ci/cd prow config files and dependencies
  .prow/laboratory-service.yaml
  .prow/patient-service.yaml
  .prow/user-service.yaml
  laboratory-service/pom.xml
  patient-service/pom.xml
  user-service/pom.xml
Labels: size/XL

#143 [test2] ci/cd prow
  .prow/laboratory-service.yaml
  .prow/patient-service.yaml
  .prow/user-service.yaml
  laboratory-service/pom.xml
  patient-service/pom.xml
  user-service/pom.xml
Labels: size/XL

#135 Kt3/fix
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/controller/ReferralController.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/DepartmentResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/DoctorResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/LabExamResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/UnprocessedReferralsResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/LabExamMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/ReferralMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/user/Profession.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/user/Title.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/ReferralService.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/LabExamServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/ReferralServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/utils/HttpUtils.java
  laboratory-service/src/main/resources/application-dev.yaml
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/CucumberTests.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/cucumber/referralcontroller/ReferralControllerStepsUnprocessed.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/controller/ReferralControllerTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
Labels: size/L

#150 remove certain folders from code coverage
  laboratory-service/pom.xml
  patient-service/pom.xml
  user-service/pom.xml
Labels: size/XS

#156 change pom.xml's to exclude files from coverage
  laboratory-service/pom.xml
  patient-service/pom.xml
  user-service/pom.xml
Labels: size/XS

#160 Izmenjen bootstrap podataka
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/bootstrap-data/employees.txt
Labels: kind/backend

#158 add more healthrecord tests
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/mapper/HealthRecordMapper.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HealthRecordControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/PatientControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/SchedMedExaminationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HealthRecordServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/PatientServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/SchedMedExaminationServiceTest.java
Labels: kind/backend, size/L

#161 add more unit tests for laboratory service
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/DoctorResponseList.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/controller/LabExamControllerTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/LabExamServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
Labels: size/L

#170 Izmenjen bootstrap podataka
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/bootstrap-data/employees.txt
Labels: kind/backend, size/L

#173 fixed user-service BootstrapData and lab-service ReferralRepository
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
Labels: size/XS

#171 Add new tests
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/LabExamResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/LabExamServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/ReferralServiceImpl.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/LabExamServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
Labels: size/L

#172 Dodati bootstrap podaci
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/bootstrap/BootstrapData.java
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/resources/bootstrap-data/allergyVaccines.txt
  patient-service/src/main/resources/bootstrap-data/examinations.txt
  patient-service/src/main/resources/bootstrap-data/histories.txt
  patient-service/src/main/resources/bootstrap-data/patients.txt
  patient-service/src/main/resources/bootstrap-data/schedexam.txt
  patient-service/src/test/java/com/raf/si/patientservice/integration/healthRecordController/HealthRecordControllerGetHistoriesSteps.java
Labels: kind/backend, size/L

#169 Mergovan kt3 i dodati servisi
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/WorkOrderServiceImplementation.java
  laboratory-service/src/main/resources/application-prod.yaml
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
Labels: size/L
