Repository RAF-SI-2022/Bolnica-2-Backend, pull requests merged in 2023-06, with the labels that each got.

#204 Feature/kt5
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/HospitalizationController.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/VisitController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/DischargeRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/MedicalReportRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/PatientConditionRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/VisitRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/DischargeListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/DischargeResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospPatientByHospitalListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospPatientByHospitalResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospitalisedPatientsListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospitalisedPatientsResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/MedicalReportListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/MedicalReportResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/PatientConditionListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/PatientConditionResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/VisitListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/VisitResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/http/DepartmentResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/http/DoctorResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/HospitalizationMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/VisitMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/DischargeList.java
  patient-service/src/main/java/com/raf/si/patientservice/model/HospitalRoom.java
  patient-service/src/main/java/com/raf/si/patientservice/model/MedicalReport.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Visit.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/DischargeListRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HospitalizationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/MedicalReportRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/PatientConditionRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VisitRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/DischargeFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/HospitalisedPatientSearchFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/MedicalReportFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/PatientConditionFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/DischargeSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/HospitalisedPatientSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/MedicalReportSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/PatientConditionSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/service/HospitalizationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/VisitService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalizationServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/VisitServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/HttpUtils.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HospitalizationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/VisitControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalizationServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/VisitServiceTest.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/resources/bootstrap-data/employees.txt
  user-service/src/test/java/com/raf/si/userservice/unit/controller/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
Labels: kind/backend, size/XXL

#206 Promenjeno odeljenje za nacelnika u bootstrap-u
  user-service/src/main/resources/bootstrap-data/employees.txt
Labels: kind/backend, size/XS

#210 change api prefix to be consistant to oth services
  statistics-service/app/main.py
Labels: size/XS

#213 Develop cd2
  .prow/postsubmits.yaml
  kubernetes/bolnica-2/templates/ingress.yaml
  kubernetes/bolnica-2/templates/statistics-service.yaml
  statistics-service/app/main.py
Labels: size/M

#217 Develop
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalizationServiceImpl.java
Labels: size/XS

#218 dodati mock testovi za TestServis
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/TestingControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/TestingServiceTest.java
Labels: kind/backend, size/XL

#221 Vaccination-Model: Dodadat SchedVacc model
  patient-service/src/main/java/com/raf/si/patientservice/model/ScheduledVaccinationCovid.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Vaccination.java
  patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/TestingControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/TestingServiceTest.java
Labels: kind/backend, size/L

#227 Feature/kt6
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/ScheduledTestingResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/ScheduledVaccinationResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/TestingMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/VaccinationMapper.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/configuration/SchedulerConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserResponse.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/Permission.java
  user-service/src/main/java/com/raf/si/userservice/model/Shift.java
  user-service/src/main/java/com/raf/si/userservice/model/ShiftTime.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/ShiftType.java
  user-service/src/main/java/com/raf/si/userservice/repository/ShiftRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/ShiftTimeRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
Labels: size/L

#228 Feature/kt6
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/AddShiftRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserShiftResponse.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/Shift.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/repository/ShiftRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/ShiftTimeRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
Labels: size/L

#230 Feature/kt6
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/HealthRecordController.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/VaccinationCovidController.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/bootstrap-data/employees.txt
Labels: lgtm, size/M

#229 Feature/kt6
  patient-service/src/main/java/com/raf/si/patientservice/controller/HospitalizationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/HospitalizationRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/service/HospitalizationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalizationServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HospitalizationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalizationServiceTest.java
Labels: lgtm, size/S

#232 Feature/kt6
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/SchedMedExamRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/TimeRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AvailableTermRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/TestingServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/VaccinationCovidServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/HttpUtils.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsCreate.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/SchedMedExaminationServiceTest.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/TimeRequest.java
  user-service/src/main/java/com/raf/si/userservice/model/Shift.java
  user-service/src/main/java/com/raf/si/userservice/repository/ShiftRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
Labels: size/L

#231 Rad recepcionara.
  patient-service/src/main/java/com/raf/si/patientservice/controller/TestingController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/TestResultResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/TestingRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/TestingService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/TestingServiceImpl.java
  user-service.iml
Labels: size/M

#239 Dodati CUC testovi za Vaccination Covid Service
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/ScheduledVaccinationCovidRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/VaccinationCovidServiceImpl.java
  patient-service/src/main/resources/bootstrap-data/vaccinationCovid.txt
  patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/vaccinationCovidController/VaccinationCovidControllerCreateSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/vaccinationCovidController/VaccinationCovidControllerDeleteSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/vaccinationCovidController/VaccinationCovidControllerGetSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/vaccinationCovidController/VaccinationCovidControllerUpdateSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/localTypeDefAdapters/LocalDateTimeAdapter.java
  patient-service/src/test/resources/features/vaccinationCovidController/vaccination-covid-controller-tests.feature
Labels: lgtm, kind/backend, size/XL

#246 dodate covid sobe
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
Labels: size/M

#236 Dodat model za kovid sertifikat, dodato kreiranje kovid sertifikata …
  .prow/patient-service.yaml
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/PatientServiceApplication.java
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/configuration/MailConfig.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/TestingController.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/VaccinationCovidController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/CertificatePlaceHolders.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/CovidCertificateResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/CovidCertificateMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/CovidCertificate.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/certificate/CovidCertificateType.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/CovidCertificateRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/TestingRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VaccinationCovidRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/CovidCertificateFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/CovidCertificateSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/service/CovidCertificateService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/EmailService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/TestingService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/VaccinationCovidService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/CovidCertificateServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/EmailServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/TestingServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/VaccinationCovidServiceImpl.java
  patient-service/src/main/resources/application-dev.yaml
  patient-service/src/main/resources/application-prod.yaml
  patient-service/src/main/resources/bootstrap-data/patients.txt
  patient-service/src/main/resources/certificate/Certificate_testing.pdf
  patient-service/src/main/resources/certificate/Certificate_vaccination.pdf
  patient-service/src/test/java/com/raf/si/patientservice/integration/schedMedExamcontroller/SchedMedExamControllerStepsUpdate.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/TestingControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/VaccinationCovidControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/CovidCertificateServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/EmailServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/SchedMedExaminationServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/TestingServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/VaccinationCovidServiceTest.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/EmailServiceImpl.java
  user-service/src/main/resources/application-dev.yaml
  user-service/src/main/resources/application-prod.yaml
  user-service/src/test/java/com/raf/si/userservice/unit/service/EmailServiceTest.java
Labels: kind/backend, size/XXL

#248 Dodate promene za email servis
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/EmailServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/PDFUtil.java
  patient-service/src/main/resources/certificate/arial.ttf
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/EmailServiceTest.java
Labels: size/L

#244 Kt6 covid hospital
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/HospitalRoomController.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/HospitalizationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospitalBedAvailabilityResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/model/HospitalRoom.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HospitalRoomRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/HospitalRoomService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalRoomServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/CucumberTests.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/hospitalRoomController/HospitalRoomControllerGetSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HospitalRoomControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalRoomServiceTest.java
  patient-service/src/test/resources/features/hospitalRoomController/hospital-room-controller-tests.feature
Labels: lgtm, size/L

#249 Feature/kt6
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/TestingServiceTest.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
Labels: size/XL

#247 Feature/prometheus
  docker-compose.yaml
  grafana/Dockerfile
  grafana/grafana.ini
  grafana/spring-dashboard.json
  laboratory-service/pom.xml
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/filters/AuthenticationFilter.java
  laboratory-service/src/main/resources/application-dev.yaml
  laboratory-service/src/main/resources/application-prod.yaml
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/filters/AuthenticationFilter.java
  patient-service/src/main/resources/application-dev.yaml
  patient-service/src/main/resources/application-prod.yaml
  prometheus/Dockerfile
  prometheus/prometheus.yml
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/configuration/SecurityConfig.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/resources/application-dev.yaml
  user-service/src/main/resources/application-prod.yaml
Labels: size/XXL

#250 Dodata instalacija u dockerfile
  .prow/laboratory-service.yaml
  .prow/patient-service.yaml
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
  patient-service/Dockerfile
  patient-service/src/main/java/com/raf/si/patientservice/utils/PDFUtil.java
  patient-service/src/main/resources/certificate/Certificate_vaccination.pdf
  patient-service/src/main/resources/certificate/arial.ttf
Labels: size/M

#252 gender in token claims
  user-service/src/main/java/com/raf/si/userservice/service/impl/AuthServiceImpl.java
Labels: size/XS

#254 Dodati neki integracioni testovi za user servis
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/UtilsHelper.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsGet.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsUpdate.java
  user-service/src/test/resources/features/usercontroller/user-controller-tests.feature
Labels: size/L
