Repository RAF-SI-2022/Bolnica-2-Backend, pull requests merged in 2023-05, with the labels that each got.

#192 laboratory service bugfixes and response changes
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/bootstrap/BootstrapData.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/UnprocessedReferralsResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/dto/response/order/ResultResponse.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/OrderMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/LabExamServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/ReferralServiceImpl.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/WorkOrderServiceImplementation.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/LabExamServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/ReferralServiceTest.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
  user-service/src/main/resources/bootstrap-data/employees.txt
Labels: size/L

#178 Dodati testovi
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/OrderMapper.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabWorkOrderRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/WorkOrderServiceImplementation.java
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
Labels: size/L

#193 redis fix
  docker-compose.yaml
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/ReferralServiceImpl.java
  laboratory-service/src/main/resources/application-prod.yaml
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HealthRecordServiceImpl.java
  patient-service/src/main/resources/application-prod.yaml
  user-service/src/main/java/com/raf/si/userservice/service/impl/DepartmentServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/resources/application-prod.yaml
Labels: size/M

#194 Dodati neki testovi, dodate neke provere za zakazane posete i hospita…
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/AppointmentListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/HospitalRoomListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AppointmentRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HospitalRoomRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HospitalizationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/AppointmentServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalizationServiceImpl.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/AppointmentControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HospitalRoomControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/controller/HospitalizationControllerTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalRoomServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalizationServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/PatientServiceTest.java
Labels: size/L

#196 Izmena u testu
  laboratory-service/src/test/java/com/raf/si/laboratoryservice/unit/service/WorkOrderServiceTest.java
Labels: size/XS

#197 Dodati testovi
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AppointmentRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HospitalizationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/HospitalizationServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/HttpUtils.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/appointmentController/AppointmentControllerChangeStatusSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/appointmentController/AppointmentControllerCreateSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/appointmentController/AppointmentControllerGetSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/hospitalRoomController/HospitalRoomControllerGetSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/integration/hospitalizationController/HospitalizationControllerSteps.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/AppointmentServiceTest.java
  patient-service/src/test/java/com/raf/si/patientservice/unit/service/HospitalizationServiceTest.java
  patient-service/src/test/resources/features/appointmentController/appointment-controller-tests.feature
  patient-service/src/test/resources/features/hospitalRoomController/hospital-room-controller-tests.feature
  patient-service/src/test/resources/features/hospitalizationController/hospitalization-controller-tests.feature
Labels: size/XXL

#201 Develop cd
  .prow/postsubmits.yaml
  kubernetes/bolnica-2/Chart.yaml
  kubernetes/bolnica-2/env/values-dev.yaml
  kubernetes/bolnica-2/env/values-prod.yaml
  kubernetes/bolnica-2/templates/database-lab.yaml
  kubernetes/bolnica-2/templates/database-patient.yaml
  kubernetes/bolnica-2/templates/database-user.yaml
  kubernetes/bolnica-2/templates/front-test.yaml
  kubernetes/bolnica-2/templates/ingress.yaml
  kubernetes/bolnica-2/templates/laboratory-service.yaml
  kubernetes/bolnica-2/templates/patient-service.yaml
  kubernetes/bolnica-2/templates/user-service.yaml
  kubernetes/bolnica-2/values.yaml
Labels: size/XL

#202 Develop
  .prow/postsubmits.yaml
  kubernetes/bolnica-2/Chart.yaml
  kubernetes/bolnica-2/env/values-dev.yaml
  kubernetes/bolnica-2/env/values-prod.yaml
  kubernetes/bolnica-2/templates/database-lab.yaml
  kubernetes/bolnica-2/templates/database-patient.yaml
  kubernetes/bolnica-2/templates/database-user.yaml
  kubernetes/bolnica-2/templates/front-test.yaml
  kubernetes/bolnica-2/templates/ingress.yaml
  kubernetes/bolnica-2/templates/laboratory-service.yaml
  kubernetes/bolnica-2/templates/patient-service.yaml
  kubernetes/bolnica-2/templates/user-service.yaml
  kubernetes/bolnica-2/values.yaml
Labels: size/XL
