Repository RAF-SI-2022/Bolnica-2-Backend, pull requests merged in 2023-03, with the labels that each got.

#3 Dodat kostur za korisnicki servis
  .idea/.name
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/libraries/Maven__com_google_code_gson_gson_2_10_1.xml
  user-service/.gitignore
  user-service/.mvn/wrapper/maven-wrapper.jar
  user-service/.mvn/wrapper/maven-wrapper.properties
  user-service/README.md
  user-service/mvnw
  user-service/mvnw.cmd
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/UserServiceApplication.java
  user-service/src/main/java/com/raf/si/userservice/configuration/AppConfig.java
  user-service/src/main/java/com/raf/si/userservice/exception/BadRequestException.java
  user-service/src/main/java/com/raf/si/userservice/exception/ControllerErrorHandler.java
  user-service/src/main/java/com/raf/si/userservice/exception/CustomException.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorDetails.java
  user-service/src/main/java/com/raf/si/userservice/exception/NotFoundException.java
  user-service/src/main/java/com/raf/si/userservice/exception/UnauthorizedException.java
  user-service/src/main/resources/application.yaml
  user-service/src/test/java/com/raf/si/userservice/UserServiceApplicationTests.java
Labels: kind/backend, size/XL, needs-ok-to-test

#4 Feature/init service
  .idea/.name
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/libraries/Maven__com_google_code_gson_gson_2_10_1.xml
  user-service/.gitignore
  user-service/.mvn/wrapper/maven-wrapper.jar
  user-service/.mvn/wrapper/maven-wrapper.properties
  user-service/README.md
  user-service/mvnw
  user-service/mvnw.cmd
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/UserServiceApplication.java
  user-service/src/main/java/com/raf/si/userservice/configuration/AppConfig.java
  user-service/src/main/java/com/raf/si/userservice/exception/BadRequestException.java
  user-service/src/main/java/com/raf/si/userservice/exception/ControllerErrorHandler.java
  user-service/src/main/java/com/raf/si/userservice/exception/CustomException.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorDetails.java
  user-service/src/main/java/com/raf/si/userservice/exception/NotFoundException.java
  user-service/src/main/java/com/raf/si/userservice/exception/UnauthorizedException.java
  user-service/src/main/resources/application.yaml
  user-service/src/test/java/com/raf/si/userservice/UserServiceApplicationTests.java
Labels: kind/backend

#5 model bolnice
  .DS_Store
  .idea/.name
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/libraries/Maven__com_google_code_gson_gson_2_10_1.xml
  user-service.iml
  user-service/.DS_Store
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/controller/AuthController.java
  user-service/src/main/java/com/raf/si/userservice/controller/KorisnikController.java
  user-service/src/main/java/com/raf/si/userservice/model/Korisnik.java
  user-service/src/main/java/com/raf/si/userservice/model/Odeljenje.java
  user-service/src/main/java/com/raf/si/userservice/model/Privilegije.java
  user-service/src/main/java/com/raf/si/userservice/model/Ustanova.java
  user-service/src/main/java/com/raf/si/userservice/repository/KorisnikRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/OdeljenjeRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/PrivilegijeRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UstanovaRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/KorisnikService.java
  user-service/src/main/java/com/raf/si/userservice/utils/JwtUtil.java
Labels: lgtm, size/XL, needs-ok-to-test

#7 prettify docker command
  user-service/README.md
Labels: size/XS

#11 Implementiran endpoint za kreiranje korisnika
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/configuration/AppConfig.java
  user-service/src/main/java/com/raf/si/userservice/configuration/SecurityConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/KorisnikController.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/CreateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserResponse.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorDetails.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/Department.java
  user-service/src/main/java/com/raf/si/userservice/model/Hospital.java
  user-service/src/main/java/com/raf/si/userservice/model/Korisnik.java
  user-service/src/main/java/com/raf/si/userservice/model/Odeljenje.java
  user-service/src/main/java/com/raf/si/userservice/model/Permission.java
  user-service/src/main/java/com/raf/si/userservice/model/Privilegije.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/model/Ustanova.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/Profession.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/Title.java
  user-service/src/main/java/com/raf/si/userservice/repository/DepartmentRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/HospitalRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/KorisnikRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/OdeljenjeRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/PermissionsRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/KorisnikService.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/utils/JwtUtil.java
  user-service/src/main/resources/application.yaml
Labels: kind/backend, size/XXL

#12 Feature/kt1
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/configuration/AppConfig.java
  user-service/src/main/java/com/raf/si/userservice/configuration/SecurityConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/KorisnikController.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/CreateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserResponse.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorDetails.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/Department.java
  user-service/src/main/java/com/raf/si/userservice/model/Hospital.java
  user-service/src/main/java/com/raf/si/userservice/model/Korisnik.java
  user-service/src/main/java/com/raf/si/userservice/model/Odeljenje.java
  user-service/src/main/java/com/raf/si/userservice/model/Permission.java
  user-service/src/main/java/com/raf/si/userservice/model/Privilegije.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/model/Ustanova.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/Profession.java
  user-service/src/main/java/com/raf/si/userservice/model/enums/Title.java
  user-service/src/main/java/com/raf/si/userservice/repository/DepartmentRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/HospitalRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/KorisnikRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/OdeljenjeRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/PermissionsRepository.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/KorisnikService.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/utils/JwtUtil.java
  user-service/src/main/resources/application.yaml
Labels: size/XXL

#14 endpoint za dobavljanje podataka, swagger implementiran
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/configuration/SecurityConfig.java
  user-service/src/main/java/com/raf/si/userservice/configuration/SwaggerConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/AuthController.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/LoginUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/LoginUserResponse.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/utils/JwtUtil.java
Labels: kind/backend, size/L

#25 Refaktorisan kod
  user-service/src/main/java/com/raf/si/userservice/configuration/SecurityConfig.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/CreateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/UpdateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/ListUserResponse.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
Labels: kind/backend, sprint 1

#26 Implementacija listanje zaposlenih i resetovanje sifre
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/configuration/MailConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/PasswordResetRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/CountResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/MessageResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListResponse.java
  user-service/src/main/java/com/raf/si/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/raf/si/userservice/exception/InternalServerErrorException.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/EmailService.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/EmailServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
Labels: kind/backend, sprint 1

#30 Added count for listing users and lbz
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListAndCountResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListResponse.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
Labels: kind/backend, sprint 1

#32 Code refactored
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/configuration/MailConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/UpdatePasswordRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/UpdateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/LoginUserResponse.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/java/com/raf/si/userservice/mapper/UserMapper.java
  user-service/src/main/java/com/raf/si/userservice/model/User.java
  user-service/src/main/java/com/raf/si/userservice/repository/UserRepository.java
  user-service/src/main/java/com/raf/si/userservice/service/EmailService.java
  user-service/src/main/java/com/raf/si/userservice/service/UserService.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/EmailServiceImpl.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/main/resources/application.yaml
  user-service/src/test/java/com/raf/si/userservice/UserServiceApplicationTests.java
  user-service/src/test/java/com/raf/si/userservice/unit/AuthServiceTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/EmailServiceTest.java
Labels: kind/backend, sprint 1

#33 Added tests
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/request/UpdateUserRequest.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/CountResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/MessageResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListAndCountResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserResponse.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/java/com/raf/si/userservice/service/impl/UserServiceImpl.java
  user-service/src/test/java/com/raf/si/userservice/UserServiceUnitTest.java
  user-service/src/test/java/com/raf/si/userservice/integration/AuthControllerITest.java
  user-service/src/test/java/com/raf/si/userservice/integration/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/AuthControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/AuthServiceTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/EmailServiceTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
Labels: kind/backend, sprint 1

#36 Feature/kt2
  patient-service/.mvn/wrapper/maven-wrapper.jar
  patient-service/.mvn/wrapper/maven-wrapper.properties
  patient-service/Dockerfile
  patient-service/README.md
  patient-service/mvnw
  patient-service/mvnw.cmd
  patient-service/pom.xml
  patient-service/src/main/java/com/raf/si/patientservice/PatientServiceApplication.java
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/configuration/AppConfig.java
  patient-service/src/main/java/com/raf/si/patientservice/configuration/SecurityConfig.java
  patient-service/src/main/java/com/raf/si/patientservice/configuration/SwaggerConfig.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/PatientController.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/CustomAccessDeniedHandler.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/CustomException.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/ErrorCode.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/ErrorDetails.java
  patient-service/src/main/java/com/raf/si/patientservice/filters/AuthenticationFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/Profession.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/Title.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/JwtUtil.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/TokenPayload.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/TokenPayloadUtil.java
  patient-service/src/main/resources/application.yaml
Labels: size/XXL

#64 Dodat REST endpoint za kreiranje pacijenta
  patient-service/src/main/java/com/raf/si/patientservice/PatientServiceApplication.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/PatientController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/PatientRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/PatientResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/BadRequestException.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/ControllerErrorHandler.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/ForbiddenException.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/InternalServerErrorException.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/NotFoundException.java
  patient-service/src/main/java/com/raf/si/patientservice/exception/UnauthorizedException.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/PatientMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/HealthRecord.java
  patient-service/src/main/java/com/raf/si/patientservice/model/MedicalExamination.java
  patient-service/src/main/java/com/raf/si/patientservice/model/MedicalHistory.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Operation.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Patient.java
  patient-service/src/main/java/com/raf/si/patientservice/model/Vaccination.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/patient/CountryCode.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/HealthRecordRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/PatientRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/PatientService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/PatientServiceImpl.java
Labels: size/L

#67 Dodat REST API za azuriranje statusa pregleda
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/SchedMedExamRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/UpdateSchedMedExamRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/ScheduledMedExamination.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/examination/ExaminationStatus.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/examination/PatientArrivalStatus.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/PatientRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/ScheduledMedExamRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/service/SchedMedExaminationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationImpl.java
  patient-service/src/main/resources/application.yaml
Labels: size/L

#68 Dodat REST API za azuriranje stausa o prispecu pacijenta
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/UpdateSchedMedExamRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/service/SchedMedExaminationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationImpl.java
Labels: size/M

#72 ubacen docker compose
  README.md
  docker-compose.yaml
  laboratory-service/src/main/resources/application.yaml
  patient-service/src/main/resources/application.yaml
  user-service/src/main/resources/application.yaml
Labels: kind/backend, size/M, sprint 3

#93 Dodat REST API za get schedMedExam
  patient-service/src/main/java/com/raf/si/patientservice/bootstrap/BootstrapData.java
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamListResponse.java
  patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/user/Profession.java
  patient-service/src/main/java/com/raf/si/patientservice/model/enums/user/Title.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/ScheduledMedExamRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/filter/ScheduledMedExamFilter.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/filtering/specification/ScheduledMedExamSpecification.java
  patient-service/src/main/java/com/raf/si/patientservice/service/SchedMedExaminationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
  patient-service/src/main/java/com/raf/si/patientservice/utils/HttpUtils.java
  patient-service/src/main/resources/application.yaml
Labels: size/L

#69 Dodat REST API za brisanje zakazanog pregleda
  patient-service/src/main/java/com/raf/si/patientservice/controller/SchedMedExaminationController.java
  patient-service/src/main/java/com/raf/si/patientservice/dto/request/SchedMedExamRequest.java
  patient-service/src/main/java/com/raf/si/patientservice/service/SchedMedExaminationService.java
  patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
Labels: size/M

#95 Added Cucumber tests and endpoint for getting employee information
  patient-service/Dockerfile
  patient-service/README.md
  patient-service/src/main/resources/application-dev.yaml
  patient-service/src/main/resources/application-prod.yaml
  patient-service/src/main/resources/application.yaml
  user-service/Dockerfile
  user-service/README.md
  user-service/pom.xml
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/com/raf/si/userservice/configuration/MailConfig.java
  user-service/src/main/java/com/raf/si/userservice/controller/UserController.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/LoginUserResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/MessageResponse.java
  user-service/src/main/java/com/raf/si/userservice/dto/response/UserListAndCountResponse.java
  user-service/src/main/java/com/raf/si/userservice/filters/AuthenticationFilter.java
  user-service/src/main/resources/application-dev.yaml
  user-service/src/main/resources/application-prod.yaml
  user-service/src/main/resources/application.yaml
  user-service/src/test/java/com/raf/si/userservice/cucumber/CucumberConfig.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/CucumberTests.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/UtilsHelper.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/authcontroller/AuthControllerSteps.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsCreate.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsDeleteReset.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsGet.java
  user-service/src/test/java/com/raf/si/userservice/cucumber/usercontroller/UserControllerStepsUpdate.java
  user-service/src/test/java/com/raf/si/userservice/integration/AuthControllerITest.java
  user-service/src/test/java/com/raf/si/userservice/integration/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/controller/UserControllerTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/AuthServiceTest.java
  user-service/src/test/java/com/raf/si/userservice/unit/service/UserServiceTest.java
  user-service/src/test/resources/features/authcontroller/auth-controller-tests.feature
  user-service/src/test/resources/features/usercontroller/user-controller-tests.feature
  user-service/src/test/resources/junit-platform.properties
Labels: kind/backend, size/XXL

#98 Filip filipovic/feature/kt2
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/bootstrap/BootstrapData.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/AnalysisParameter.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/AnalysisParameterResult.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/LabAnalysis.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/LabWorkOrder.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/Parameter.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/Referral.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/ScheduledLabExam.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/labworkorder/OrderStatus.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/parameter/ParameterType.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/referral/ReferralStatus.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/referral/ReferralType.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/model/enums/scheduledlabexam/ExamStatus.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/AnalysisParameterRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/AnalysisParameterResultRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabAnalysisRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/LabWorkOrderRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ParameterRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ReferralRepository.java
  laboratory-service/src/main/java/com/raf/si/laboratoryservice/repository/ScheduledLabExamRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AllergenRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/AllergyRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/DiagnosisRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/MedicalExaminationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/MedicalHistoryRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/OperationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VaccinationRepository.java
  patient-service/src/main/java/com/raf/si/patientservice/repository/VaccineRepository.java
  user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
Labels: size/XL
